# Generated by Django 5.0.6 on 2024-06-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_dislike',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'like'), (2, 'dislike')], null=True),
        ),
    ]
