# Generated by Django 5.0.6 on 2024-06-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_comment_like_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/AdminLTELogo.jpg', upload_to='user_images'),
        ),
    ]
