# Generated by Django 5.0.6 on 2024-06-11 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_comment_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart_item',
            unique_together={('cart', 'item')},
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='buyer',
        ),
    ]
