# Generated by Django 5.0.6 on 2024-06-11 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_cart_item_unique_together_shopping_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cart', to='backend.productvariant'),
        ),
    ]
