# Generated by Django 5.0.6 on 2024-06-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
