# Generated by Django 5.0.6 on 2024-06-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_employee_user_alter_manager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficent',
            name='password',
        ),
        migrations.RemoveField(
            model_name='beneficent',
            name='phone_number',
        ),
    ]
